/**
 * Cube configuration for InsightAI.
 *
 * Data models are NOT files on disk — they are generated by the FastAPI
 * backend from dataset metadata (Postgres) and fetched here at
 * schema-compile time. Recompilation happens whenever the backend bumps
 * its schema version (dataset ready / semantic model edited).
 *
 * Tenancy: the backend signs each API request with a JWT containing
 * { user_id, dataset_cubes }. queryRewrite rejects any query touching a
 * cube outside that list.
 */

const MODELS_URL = process.env.CUBEJS_MODELS_URL || 'http://backend:8000/api/v1/internal/cube';
const INTERNAL_TOKEN = process.env.CUBE_INTERNAL_TOKEN || '';

async function fetchInternal(path) {
  const res = await fetch(`${MODELS_URL}${path}`, {
    headers: { 'x-internal-token': INTERNAL_TOKEN },
  });
  if (!res.ok) {
    throw new Error(`InsightAI models endpoint ${path} responded ${res.status}`);
  }
  return res.json();
}

module.exports = {
  schemaVersion: async () => {
    try {
      const body = await fetchInternal('/schema-version');
      return String(body.version);
    } catch (e) {
      console.error('schemaVersion fetch failed:', e.message);
      return 'backend-unavailable';
    }
  },

  repositoryFactory: () => ({
    dataSchemaFiles: async () => {
      const body = await fetchInternal('/models');
      return (body.files || []).map((f) => ({
        fileName: f.fileName,
        content: f.content,
      }));
    },
  }),

  queryRewrite: (query, { securityContext }) => {
    const allowed = new Set(
      (securityContext && securityContext.dataset_cubes) || []
    );
    const members = [
      ...(query.measures || []),
      ...(query.dimensions || []),
      ...(query.timeDimensions || []).map((t) => t.dimension),
      ...(query.filters || []).map((f) => f.member).filter(Boolean),
    ];
    for (const member of members) {
      const cube = String(member).split('.')[0];
      if (!allowed.has(cube)) {
        throw new Error(`Access denied for cube: ${cube}`);
      }
    }
    return query;
  },
};
